spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myTemp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: zxc5201314


mybatis-plus:
  config-location:
    classpath: mapper/*.xml

server:
  port: 8081
